// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/cheonsy/lattigo/gpu-core/BindingTest/goFile/num.go:1:1
package num

// #cgo CFLAGS: -I/cheonsy/home/lattigo/gpu-core/BindingTest/src/include
// #cgo LDFLAGS: -L/cheonsy/home/latiigo/gpu-core/BindingTest/src
// #include "/home/cheonsy/lattigo/gpu-core/BindingTest/src/include/num.h"
import _ "unsafe"
import (
	"unsafe"
)

type GoNum struct {
	num  /*line :12:6*/_Ctype_Num /*line :12:11*/
}

func New() GoNum {
	var ret GoNum
	ret.num = ( /*line :17:12*/_Cfunc_NumInit /*line :17:20*/)()
	return ret
}
func (n GoNum) Free() {
	func() { _cgo0 := /*line :21:12*/(_Ctype_Num /*line :21:18*/)(unsafe.Pointer(n.num)); _cgoCheckPointer(_cgo0, nil); _Cfunc_NumFree(_cgo0); }()
}
func (n GoNum) Inc() {
	func() { _cgo0 := /*line :24:17*/(_Ctype_Num /*line :24:23*/)(unsafe.Pointer(n.num)); _cgoCheckPointer(_cgo0, nil); _Cfunc_NumIncrement(_cgo0); }()
}
func (n GoNum) GetValue() int {
	return int(func() _Ctype_int{ _cgo0 := /*line :27:27*/(_Ctype_Num /*line :27:33*/)(unsafe.Pointer(n.num)); _cgoCheckPointer(_cgo0, nil); return _Cfunc_NumGetValue(_cgo0); }())
}
